# https://taskfile.dev

version: "3"

vars:
  GITHUB_REPOSITORY_OWNER: muehlemann-popp
  GCP_PROJECT_ID: crowdtransfer-mp
  GCP_SERVICE_ACCOUNT: sa-gitlab-crowdtransfer@crowdtransfer-mp.iam.gserviceaccount.com
  DRY_RUN: true
  SAVE_DATA: true
  FILE_MODE: false

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  poetry:install:
    desc: Install dependencies without changes in lock file
    cmds:
      - poetry install --sync -v

  poetry:install:ci:
    desc: Install dependencies like in CI pipeline
    cmds:
      - poetry install --sync -v --without=dev

  poetry:install:update:
    desc: Update dependencies with 'poetry'
    cmds:
      - poetry update

  gcloud:project:set:
    desc: Set current project in gcloud context
    cmds:
      - gcloud config set project {{ .GCP_PROJECT_ID }}

  gcloud:project:get:
    desc: Get current project from gcloud context
    cmds:
      - gcloud config get project

  py:format:
    desc: Format python files
    cmds:
      - poetry run ruff check --select I --fix
      - poetry run ruff format

  py:run:
    env:
      DRY_RUN: "{{ .DRY_RUN }}"
      SAVE_DATA: "{{ .SAVE_DATA }}"
      FILE_MODE: "{{ .FILE_MODE }}"
    desc: Run main script with poetry
    cmd: poetry run python ./main.py
