# https://taskfile.dev

version: "3"

vars:
  GITHUB_REPOSITORY_OWNER: muehlemann-popp
  GITHUB_REPOSITORY_NAME: tempo-vacation-syncher
  GCP_PROJECT_ID: tempo-vacation-syncher
  GCP_SERVICE_ACCOUNT: github-ci@tempo-vacation-syncher.iam.gserviceaccount.com
  GCP_IDENTITY_POOL_ID: github-identity-pool
  GCP_DOCKER_IMAGE_NAME: europe-west6-docker.pkg.dev/tempo-vacation-syncher/tempo-vacation-syncher/build

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  uv:install:
    desc: Install dependencies without changes in lock file
    cmds:
      - uv sync --frozen -v --all-groups

  uv:install:ci:
    desc: Install dependencies like in CI pipeline
    cmds:
      - uv sync --frozen -v --no-dev

  uv:install:update:
    desc: Update dependencies with 'uv'
    cmds:
      - uv sync --upgrade -v

  gcloud:project:set:
    desc: Set current project in gcloud context
    cmds:
      - gcloud config set project {{ .GCP_PROJECT_ID }}

  gcloud:project:get:
    desc: Get current project from gcloud context
    cmds:
      - gcloud config get project

  py:format:
    desc: Format python files
    cmds:
      - uv run ruff check --select I --fix
      - uv run ruff format

  py:run:
    desc: Run main script with uv
    cmd: uv run python ./main.py
